### ISSUE TITLE
Memory leak that affects Word memory usage

### ISSUE THREAD

**Issue by dbalabka** [adomasven/zotero-word-js-integration#1]
I've noticed high memory usage of Word. I conclude that it is related to Zotero because, during stopping Word, Zotero reported that some of the scripts hung and provided an option to stop it. Unfortuately, I don't have more details but I'll try to find step to reproduce.
![image](https://github.com/user-attachments/assets/0a30d1c6-ee06-4d5a-a96d-9061a218c049)

**Comment by adomasven** [comment]
Please post all feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org). See [CONTRIBUTING.md](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md) and [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.
